- name: Prueba usuario y contraseña
  hosts: localhost
  tasks:
  - name: Usuario
    debug: msg="the secret is '{{ ANSIBLE_NET_USERNAME }}'"
  - name: Contraseña
    debug: msg="the secret is '{{ ANSIBLE_NET_PASSWORD }}'"
