- name: Prueba usuario y contraseña
  hosts: localhost
  tasks:
  - name: Usuario
    debug: msg="it is '{{ o365_username }}'"

  - name: Contraseña
    debug: msg="the secret is '{{ o365_password }}'"
    no_log: true
    
  - name: Ping!
    ping:
